name: cloudsmith_release

on:
  push:
  workflow_dispatch:

jobs:
  cloudsmith_release:
    uses: killbill/gh-actions-shared/.github/workflows/cloudsmith_release.yml@main
    with:
      group_id: org.kill-bill.billing.plugin.java
      artifact_id: analytics-plugin
    secrets:
      CLOUDSMITH_REPO: ${{ secrets.CLOUDSMITH_REPO }}
      CLOUDSMITH_USER: ${{ secrets.CLOUDSMITH_USER }}
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
